services:
  - type: web
    name: django-book-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bookapp.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
